#!/usr/bin/env python3
# Pitivi video editor
#
#       pitivi
#
# Copyright (c) 2015, Thibault Saunier <tsaunier@gnome.org>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, write to the
# Free Software Foundation, Inc., 51 Franklin St, Fifth Floor,
# Boston, MA 02110-1301, USA.
import os
import gi.overrides

if __name__ == "__main__":
    os.environ["PYTHONPATH"] = "/app/lib/python3.3/site-packages/"
    gi.overrides.__path__.insert(0, "/app/lib/python3.3/site-packages/gi/")

    with open("/app/bin/pitivi") as f:
        code = compile(f.read(), "pitivi", 'exec')
        exec(code, globals(), None)
